version: "3.7"
services:
  db:
    image: postgres:12.2
    container_name: webDesignTutsDb
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    build: ./api
    container_name: webDesignTutsApi
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - webDesignTutsDb
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=db
      - DB_PORT=5432
      - DATABASE_URL=postgres://user:password@db:5432/db?schema=public
    volumes:
      - ./api:/usr/src/app
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 5173:5173
    depends_on:
      - webDesignTutsApi
      - webDesignTutsDb
    environment:
      - VITE_AXIOS_BASE_URL=http://localhost:3000
    volumes:
      - ./frontend:/usr/src/app
    container_name: webDesignTutsFrontend
